### ISSUE TITLE
Does not work in iOS FB right now

### ISSUE THREAD

**Issue by ryancwalsh** [huantt/force-open-browser#1]
I was very excited to find your project because it's exactly what I want to do. Thank you for providing it.

However, I pasted https://huanttdev.firebaseapp.com/force-open-browser into a Facebook comment and then clicked that link from within the Facebook app on iPhone, and it did NOT pop out into another browser. 

Instead I see "Page contents..." within the FB browser.

**Comment by ryancwalsh** [comment]
I think this is on the right track:

    const target = "mypage.com";
    const browserScheme = "googlechromes://";//https://apple.stackexchange.com/a/142844/53510
    var iframeContainerDiv = document.createElement("div");
    iframeContainerDiv.innerHTML = `<iframe src='${browserScheme}${target}' style='width:0;height:0;border:0; border:none;visibility: hidden;'></iframe>`;
    document.body.appendChild(iframeContainerDiv);

But I'd want to wrap it in a function that somehow could try Chrome and then Safari if Chrome wasn't available, and I'd want to make sure it works on both iOS and Android and other systems.

**Comment by huantt** [comment]
Hi guy, If you want to use it on IOS, you can pass chrome scheme to openInBrowser.
Chrome scheme URL on IOS  is `googlechrome://`

**Comment by huantt** [comment]
If you want to work with the both Android and IOS, you can detect device OS by user agent then choose the corresponding scheme.
You can see how to detect device OS in here: https://stackoverflow.com/questions/21741841/detecting-ios-android-operating-system
