### ISSUE TITLE
Does not work in Android Facebook App actually

### ISSUE THREAD

**Issue by swapfile** [huantt/force-open-browser#2]

**Comment by huantt** [comment]
Pls click to the following link then show me the user-agent:
https://www.whatsmyua.info

**Comment by aklein13** [comment]
@huantt 
The user-agent from facebook app didn't change (`Mozilla/5.0 (Linux; Android 8.0.0; Android SDK built for x86 Build/OSR1.170901.043; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/77.0.3865.116 Mobile Safari/537.36 [FB_IAB/FB4A;FBAV/242.0.0.43.119;]`) so it's still getting detected by your function. 
Even if I try to open it via `window.location.replace('googlechrome://navigate?url=example.com');` it doesn't work even tho the same method worked for my other mobile app a few days ago.
Chrome deep link works from deep link test app so my chrome is getting detected.
So it's more like facebook blocked deep links?

I recorded this so feel free to take a look: https://youtu.be/A7MXkt2yr5o
It's from emulator (android 10) but it behaves exactly the same on real device (android 6), it was just easier to record.

Tell me if you'll find a solution for that but I doubt there is anything we can do to make it work.

**Comment by huantt** [comment]
Thank for your information.
Sorry I don't have Android device right now, I will test this case again.

**Comment by huantt** [comment]
Look like loading by iframe no longer possible from Chrome for Android version 25 and later.
So sorry about that, I will try to find some ways to handle this.
If you have any way, let discuss together.
Thanks!

https://developer.chrome.com/multidevice/android/intents

**Comment by iwex** [comment]
@huantt any news regarding this?

**Comment by huantt** [comment]
> @huantt any news regarding this?

**Comment by huantt** [comment]
Since Google Chrome updated, we can no longer do it.
